### ISSUE TITLE
Suggestion: add an unload model function

### ISSUE THREAD

**Issue by kiron111** [SeanScripts/ComfyUI-PixtralLlamaMolmoVision#9]
It would be nice to a function " unload model after generate" function to the node, 
as we may use flux(or other Dit) to generate images after the prompt is generated.

thanks!!

**Comment by SeanScripts** [comment]
Yeah, I need to figure out how to integrate with the ComfyUI model
management better. The way I'm currently loading the model is independent
of that, so the usual "unload models" button (or the UnloadModel node)
doesn't work at the moment.

I did try adding something to unload it manually after generating, but that
ran into another issue: It would only work once, because the model loading
node had a cached result somehow. It didn't think it needed to reload the
model, and then it would get an error trying to generate text for the next
prompt because the model had been deleted.

**Comment by kiron111** [comment]
thankyou for you reply and help,
another molmo node has added this function, maybe it help to give some clue:
https://github.com/CY-CHENYUE/ComfyUI-Molmo/blob/master/Molmo7BDbnb.py

**Comment by SeanScripts** [comment]
Okay, fixed. Now it also doesn't fully load the model until needed.

**Comment by kiron111** [comment]
thankyou very much
